version: '3'
services:
  postgres:
    image: postgres:14
    volumes:
      - ./database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=airflow
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready -d db -U airflow"]
      interval: 5s
      retries: 5
    restart: always


  scheduler:
    build: .
    command: poetry run airflow scheduler
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:password@postgres:5432/db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor # In production you would use other values for distributed processing etc...
    volumes:
      - ./dags/:/app/airflow/dags
      - ./data /:/app/airflow/data
      - ./logs /:/app/airflow/logs
      - .app/:/app/


  webserver:
      build: .
      command: poetry run /app/airflow/entrypoint.sh
      depends_on:
        - postgres
        - scheduler
      volumes:
        - ./dags/:/app/airflow/dags
        - ./data /:/app/airflow/data
        - ./logs /:/app/airflow/logs
      environment:
        - POSTGRES_DB=db
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_USER=airflow
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:password@postgres:5432/db
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      ports:
        - "8080:8080"
      restart: on-failure
      healthcheck:
        test: ["CMD", "-f", "/home/airflow/airflow-webserver.pid"]
        interval: 30s
        timeout: 30s
        retries: 3
