services:
    db:
        container_name: velib_db
        image: postgres:14
        ports:
            - "5410:5432"
        environment:
            - POSTGRES_DB=velib
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=$POSTGRES_USER
        volumes:
            - velib:/var/lib/postgresql/data
            - ./sql/iniit_velib_db.sql:/docker-entrypoint-initdb.d/iniit_velib_db.sql
        restart: always


volumes:
  velib:
    name: velib
