dbt_velib:
  outputs:
    dev:
      dataset: velib
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      priority: interactive
      project: "{{ env_var('GBQ_PROJECT_ID') }}"
      threads: 1
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('DBT_KEYFILE_PATH', '~/.gcp_keys/velib.json') }}"
  target: dev
