dbt_velib:
  outputs:
    dev:
      dataset: velib
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/eo/.gcp_keys/velib.json
      location: europe-west1
      method: service-account
      priority: interactive
      project: dataengvelibforecast
      threads: 1
      type: bigquery
  target: dev
